Consistent error messages. Suppress sudo complaints when merely testing for access.

diff --git a/hooks/halt b/hooks/halt
--- a/hooks/halt
+++ b/hooks/halt
@@ -4,9 +4,9 @@
 
 echo "$0: trying to halt the machine" >&2
 
-if sudo -n -l /sbin/halt >/dev/null; then
+if sudo -n -l /sbin/halt >/dev/null 2>&1; then
   sudo -n /sbin/halt
 else
-  echo "$0: no permission to attempt a halt" >&2
+  echo "$0: missing sudo permissions" >&2
   exit 1
 fi
diff --git a/hooks/reboot b/hooks/reboot
--- a/hooks/reboot
+++ b/hooks/reboot
@@ -4,9 +4,9 @@
 
 echo "$0: trying to reboot the machine" >&2
 
-if sudo -n -l /sbin/reboot >/dev/null; then
+if sudo -n -l /sbin/reboot >/dev/null 2>&1; then
   sudo -n /sbin/reboot
 else
-  echo "$0: no permission to attempt a reboot" >&2
+  echo "$0: missing sudo permissions" >&2
   exit 1
 fi
